-- =====================================================================
-- Administración y Finanzas · Contabilidad UY — pagos parciales: aplicaciones pago ↔ factura (oct 2026)
-- Proyecto Supabase: wcpkpwxhqdcdljfwzcmy. Correr A MANO en el SQL Editor ANTES de publicar el index.html
-- que usa adminfin_cuy_aplicaciones (después de los SQL anteriores de Contabilidad UY).
--
-- Qué hace:
--   Hasta ahora cada factura se unía con UN movimiento (adminfin_contabilidad_uy.movimiento_id), por el total.
--   Una factura pagada en varias veces (ej. ROMULO A-4: US$ 866 = 433 el 07/08 + 433 el 21/08) no se podía conciliar.
--   1. Tabla adminfin_cuy_aplicaciones: cuánto de cada movimiento se aplica a cada factura
--      (importe en la moneda de la cuenta del movimiento). Una factura puede tener varios pagos y un pago
--      puede cancelar varias facturas. El saldo de la factura = total − lo aplicado.
--      importe vacío = el total de la factura (solo para los vínculos que se pasan desde movimiento_id).
--   2. Pasa los vínculos ya hechos (movimiento_id) a la tabla nueva y deja movimiento_id vacío
--      (la columna queda, pero la pantalla ya no la usa).
--   Acceso: igual que el resto de Contabilidad UY.
--
-- Reversible (vuelve a 1 movimiento por factura, se pierden los pagos parciales):
--   update public.adminfin_contabilidad_uy c set movimiento_id = a.movimiento_id
--     from (select distinct on (comprobante_id) comprobante_id, movimiento_id from public.adminfin_cuy_aplicaciones order by comprobante_id, creado_en) a
--     where a.comprobante_id = c.id;
--   drop table public.adminfin_cuy_aplicaciones;
-- =====================================================================

begin;

create table if not exists public.adminfin_cuy_aplicaciones (
  id               bigint generated by default as identity primary key,
  movimiento_id    text not null references public.adminfin_cuy_movimientos(id) on delete cascade,
  comprobante_id   text not null references public.adminfin_contabilidad_uy(id) on delete cascade,
  importe          numeric,          -- en la moneda de la cuenta del movimiento; vacío = total de la factura
  creado_en        timestamptz not null default now(),
  creado_por       text,
  actualizado_en   timestamptz not null default now(),
  actualizado_por  text,
  unique (movimiento_id, comprobante_id)
);
create index if not exists adminfin_cuy_apl_comp on public.adminfin_cuy_aplicaciones (comprobante_id);

drop trigger if exists adminfin_cuy_apl_audit on public.adminfin_cuy_aplicaciones;
create trigger adminfin_cuy_apl_audit before insert or update on public.adminfin_cuy_aplicaciones
  for each row execute function public.adminfin_contabilidad_uy_audit();

alter table public.adminfin_cuy_aplicaciones enable row level security;
revoke all on public.adminfin_cuy_aplicaciones from anon;
grant select, insert, update, delete on public.adminfin_cuy_aplicaciones to authenticated;
do $$ begin   -- secuencia del id (identity): el nombre lo resuelve la base
  execute format('grant usage, select on sequence %s to authenticated', pg_get_serial_sequence('public.adminfin_cuy_aplicaciones', 'id'));
end $$;

drop policy if exists adminfin_cuyapl_sel on public.adminfin_cuy_aplicaciones;
drop policy if exists adminfin_cuyapl_ins on public.adminfin_cuy_aplicaciones;
drop policy if exists adminfin_cuyapl_upd on public.adminfin_cuy_aplicaciones;
drop policy if exists adminfin_cuyapl_del on public.adminfin_cuy_aplicaciones;
create policy adminfin_cuyapl_sel on public.adminfin_cuy_aplicaciones for select to authenticated
  using (public.tiene_sector('adminfin'::public.sector_portal));
create policy adminfin_cuyapl_ins on public.adminfin_cuy_aplicaciones for insert to authenticated
  with check (public.puede_editar_sector('adminfin'::public.sector_portal));
create policy adminfin_cuyapl_upd on public.adminfin_cuy_aplicaciones for update to authenticated
  using (public.puede_editar_sector('adminfin'::public.sector_portal))
  with check (public.puede_editar_sector('adminfin'::public.sector_portal));
create policy adminfin_cuyapl_del on public.adminfin_cuy_aplicaciones for delete to authenticated
  using (public.puede_editar_sector('adminfin'::public.sector_portal));

-- Vínculos existentes → aplicaciones por el total (importe vacío)
insert into public.adminfin_cuy_aplicaciones (movimiento_id, comprobante_id, importe)
select c.movimiento_id, c.id, null
  from public.adminfin_contabilidad_uy c
 where c.movimiento_id is not null
on conflict (movimiento_id, comprobante_id) do nothing;
update public.adminfin_contabilidad_uy set movimiento_id = null where movimiento_id is not null;

commit;

-- Verificación: la tabla con RLS (true) y cuántas aplicaciones quedaron
select relname, relrowsecurity from pg_class where relname = 'adminfin_cuy_aplicaciones';
select count(*) as aplicaciones from public.adminfin_cuy_aplicaciones;
